START TRANSACTION;

CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    NAME VARCHAR(24) NOT NULL UNIQUE,
    EMAIL VARCHAR(128) NOT NULL UNIQUE,
    EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT 0,
    EMAIL_VERIFICATION_CODE TEXT NOT NULL /*DEFAULT (HEX(UUID_TO_BIN(UUID())))*/, 
    PASSWORD VARCHAR(64) NOT NULL,
    REGISTRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SKIN SMALLINT UNSIGNED NOT NULL,
    SEX BOOLEAN NOT NULL,
    MONEY INT NOT NULL DEFAULT 0,
    XP INT UNSIGNED NOT NULL DEFAULT 0,
    LEVEL SMALLINT UNSIGNED NOT NULL DEFAULT 1,

    HEALTH INT NOT NULL DEFAULT 100,
    ARMOR INT NOT NULL DEFAULT 0,
    HUNGER FLOAT NOT NULL DEFAULT 0.0,
    THIRST FLOAT NOT NULL DEFAULT 0.0,

    POS_X FLOAT NOT NULL,
    POS_Y FLOAT NOT NULL,
    POS_Z FLOAT NOT NULL,
    ANGLE FLOAT NOT NULL,
    VIRTUAL_WORLD INT NOT NULL DEFAULT 0,
    INTERIOR TINYINT NOT NULL DEFAULT 0,

    ADMIN_LEVEL TINYINT UNSIGNED NOT NULL DEFAULT 0,

    CURRENT_PLAYERID SMALLINT NOT NULL DEFAULT -1,
    CURRENT_CONNECTION INTEGER UNSIGNED NOT NULL DEFAULT 0,
    PLAYED_TIME INTEGER UNSIGNED NOT NULL DEFAULT 0,
    CONFIG_BITS TEXT NOT NULL DEFAULT '0',

    GANG_ID INT UNSIGNED DEFAULT NULL,
    GANG_RANK TINYINT UNSIGNED DEFAULT 0
);

UPDATE `ACCOUNT` SET `CURRENT_CONNECTION` = 0, `CURRENT_PLAYERID` = -1;

CREATE TABLE IF NOT EXISTS CONNECTION_LOG (
    ACCOUNT_ID INT UNSIGNED NOT NULL,
    IP_ADDRESS VARCHAR(16) NOT NULL,
    DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PLAYER_VEHICLES (
    VEHICLE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    OWNER_ID INT UNSIGNED NOT NULL,
    MODEL SMALLINT NOT NULL,
    HEALTH FLOAT NOT NULL DEFAULT 1000.0,
    FUEL FLOAT NOT NULL DEFAULT 0.0,
    PANELS_STATUS INT NOT NULL DEFAULT 0,
    DOORS_STATUS INT NOT NULL DEFAULT 0,
    LIGHTS_STATUS INT NOT NULL DEFAULT 0,
    TIRES_STATUS INT NOT NULL DEFAULT 0,
    COLOR_ONE INT NOT NULL,
    COLOR_TWO INT NOT NULL,
    PAINTJOB INT NOT NULL DEFAULT 3,
    POS_X FLOAT NOT NULL,
    POS_Y FLOAT NOT NULL,
    POS_Z FLOAT NOT NULL,
    ANGLE FLOAT NOT NULL,
    INTERIOR INT NOT NULL DEFAULT 0,
    VW INT NOT NULL DEFAULT 0,
    COMPONENTS VARCHAR(69) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0',
    PARAMS TINYINT NOT NULL DEFAULT 0b000000,

    FOREIGN KEY(OWNER_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PLAYER_WEAPONS (
    ACCOUNT_ID INT UNSIGNED NOT NULL,
    SLOT_0 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_1 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_2 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_3 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_4 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_5 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_6 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_7 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_8 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_9 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_10 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_11 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_12 INT UNSIGNED NOT NULL DEFAULT 0,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BANK_ACCOUNT (
	ACCOUNT_ID INT UNSIGNED NOT NULL,
    BALANCE INT NOT NULL DEFAULT 0,

	FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BANK_TRANSACTIONS (
    ID_TRANSACTION INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ACCOUNT_ID INT UNSIGNED NOT NULL,
    TRANSACTION_TYPE INT NOT NULL,
    AMOUNT INT NOT NULL DEFAULT 0,
    EXTRA INT NOT NULL DEFAULT 0,
	DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PLAYER_INVENTORY (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ACCOUNT_ID INT UNSIGNED NOT NULL,
    ITEM_TYPE INT NOT NULL,
    AMOUNT INT NOT NULL DEFAULT 1,
    EXTRA INT NOT NULL DEFAULT 0,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BANS (
    BANNED_USER VARCHAR(24) NOT NULL UNIQUE,
    BANNED_IP VARCHAR(16) DEFAULT NULL,
    ADMIN_ID INT UNSIGNED DEFAULT NULL,
    REASON TEXT NOT NULL DEFAULT 'No especificada',
    ISSUED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRATION_DATE DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS POLICE_OFFICERS (
    ACCOUNT_ID INT UNSIGNED PRIMARY KEY NOT NULL,
    RECRUITED_BY INT UNSIGNED NOT NULL,
    RECRUITED_ON DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RANK TINYINT UNSIGNED NOT NULL DEFAULT 1,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE/*,
    FOREIGN KEY(RECRUITED_BY) REFERENCES ACCOUNT(ID)*/
);

CREATE TABLE IF NOT EXISTS ZONES (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	ZONE VARCHAR(8) NOT NULL,
	PART VARCHAR(8) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	MIN_X FLOAT NOT NULL,
	MIN_Y FLOAT NOT NULL,
	MIN_Z FLOAT NOT NULL,
	MAX_X FLOAT NOT NULL,
	MAX_Y FLOAT NOT NULL,
	MAX_Z FLOAT NOT NULL,
	GANG_ZONE BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS GANGS (
    GANG_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CREATOR_ID INT UNSIGNED NOT NULL, 
    GANG_NAME VARCHAR(64) NOT NULL /*DEFAULT 'Club de la Milanesa'*/,
    GANG_COLOR INT NOT NULL DEFAULT -1,
    GANG_ICON TINYINT UNSIGNED NOT NULL DEFAULT 0,

    FOREIGN KEY(CREATOR_ID) REFERENCES ACCOUNT(ID)
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_ACCOUNT_GANG` FOREIGN KEY IF NOT EXISTS (GANG_ID) REFERENCES GANGS(GANG_ID) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS GANG_RANKS (
    RANK_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    GANG_ID INT UNSIGNED NOT NULL,
    RANK_NAME VARCHAR(32) NOT NULL,
    RANK_HIERARCHY TINYINT UNSIGNED NOT NULL DEFAULT 0,
    RANK_PERMISSIONS INT NOT NULL DEFAULT 0,

    FOREIGN KEY(GANG_ID) REFERENCES GANGS(GANG_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GANG_TERRITORIES (
	GANG_ID INT UNSIGNED NOT NULL DEFAULT 0,
    TERRITORY_ID INT UNSIGNED NOT NULL,
	FOREIGN KEY(TERRITORY_ID) REFERENCES ZONES(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMPONENTS_INFO (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	PART VARCHAR(24) NOT NULL,
	NAME VARCHAR(24) NOT NULL,
    PRICE INT UNSIGNED DEFAULT NULL DEFAULT 100,
    CAMERA_TYPE INT UNSIGNED DEFAULT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS VEHICLE_COMPONENTS (
	MODELID INT UNSIGNED DEFAULT NULL,
	COMPONENT_ID INT UNSIGNED DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PAYMENTS (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    UUID VARCHAR(36) NOT NULL UNIQUE,
	ACCOUNT_ID INT UNSIGNED NOT NULL,
    STATE INT NOT NULL DEFAULT 0,
    PRODUCT INT NOT NULL DEFAULT 0,
    DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);
COMMIT;