CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    NAME VARCHAR(24) NOT NULL UNIQUE,
    EMAIL VARCHAR(128) NOT NULL UNIQUE,
    EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT 0,
    EMAIL_VERIFICATION_CODE TEXT NOT NULL /*DEFAULT (HEX(UUID_TO_BIN(UUID())))*/, 
    PASSWORD VARCHAR(64) NOT NULL,
    REGISTRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SKIN SMALLINT UNSIGNED NOT NULL,
    SEX BOOLEAN NOT NULL,
    MONEY INT NOT NULL DEFAULT 0,
    XP INT UNSIGNED NOT NULL DEFAULT 0,
    LEVEL SMALLINT UNSIGNED NOT NULL DEFAULT 1,

    HEALTH INT NOT NULL DEFAULT 100,
    ARMOR INT NOT NULL DEFAULT 0,
    HUNGER FLOAT NOT NULL DEFAULT 0.0,
    THIRST FLOAT NOT NULL DEFAULT 0.0,

    POS_X FLOAT NOT NULL,
    POS_Y FLOAT NOT NULL,
    POS_Z FLOAT NOT NULL,
    ANGLE FLOAT NOT NULL,
    VIRTUAL_WORLD INT NOT NULL DEFAULT 0,
    INTERIOR TINYINT NOT NULL DEFAULT 0,

    ADMIN_LEVEL TINYINT UNSIGNED NOT NULL DEFAULT 0,

    CURRENT_PLAYERID INTEGER UNSIGNED NOT NULL DEFAULT 0,
    CURRENT_CONNECTION INTEGER UNSIGNED NOT NULL DEFAULT 0,
    PLAYED_TIME INTEGER UNSIGNED NOT NULL DEFAULT 0
);

UPDATE `ACCOUNT` SET `CURRENT_CONNECTION` = 0, `CURRENT_PLAYERID` = 0;

CREATE TABLE IF NOT EXISTS CONNECTION_LOG (
    ACCOUNT_ID INT UNSIGNED NOT NULL,
    IP_ADDRESS VARCHAR(16) NOT NULL,
    DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PLAYER_VEHICLES (
    VEHICLE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    OWNER_ID INT UNSIGNED NOT NULL,
    MODEL SMALLINT NOT NULL,
    HEALTH FLOAT NOT NULL DEFAULT 1000.0,
    FUEL FLOAT NOT NULL DEFAULT 0.0,
    PANELS_STATUS INT NOT NULL DEFAULT 0,
    DOORS_STATUS INT NOT NULL DEFAULT 0,
    LIGHTS_STATUS INT NOT NULL DEFAULT 0,
    TIRES_STATUS INT NOT NULL DEFAULT 0,
    COLOR_ONE INT NOT NULL,
    COLOR_TWO INT NOT NULL,
    PAINTJOB INT NOT NULL DEFAULT 0,
    POS_X FLOAT NOT NULL,
    POS_Y FLOAT NOT NULL,
    POS_Z FLOAT NOT NULL,
    ANGLE FLOAT NOT NULL,
    INTERIOR INT NOT NULL DEFAULT 0,
    VW INT NOT NULL DEFAULT 0,
    COMPONENTS VARCHAR(69) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0',
    PARAMS TINYINT NOT NULL DEFAULT 0b000000,

    FOREIGN KEY(OWNER_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PLAYER_WEAPONS (
    ACCOUNT_ID INT UNSIGNED NOT NULL,
    SLOT_1 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_2 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_3 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_4 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_5 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_6 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_7 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_8 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_9 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_10 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_11 INT UNSIGNED NOT NULL DEFAULT 0,
    SLOT_12 INT UNSIGNED NOT NULL DEFAULT 0,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BANK_ACCOUNT (
	ACCOUNT_ID INT UNSIGNED NOT NULL,
    BALANCE INT NOT NULL DEFAULT 0,

	FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BANK_TRANSACTIONS (
    ID_TRANSACTION INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ACCOUNT_ID INT UNSIGNED NOT NULL,
    TRANSACTION_TYPE INT NOT NULL,
    AMOUNT INT NOT NULL DEFAULT 0,
    EXTRA INT NOT NULL DEFAULT 0,
	DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PLAYER_INVENTORY (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ACCOUNT_ID INT UNSIGNED NOT NULL,
    ITEM_TYPE INT NOT NULL,
    AMOUNT INT NOT NULL DEFAULT 1,
    EXTRA INT NOT NULL DEFAULT 0,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);