CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    NAME VARCHAR(24) NOT NULL UNIQUE,
    EMAIL VARCHAR(128) NOT NULL UNIQUE,
    EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT 0,
    EMAIL_VERIFICATION_CODE TEXT NOT NULL /*DEFAULT (HEX(UUID_TO_BIN(UUID())))*/, 
    PASSWORD VARCHAR(64) NOT NULL,
    REGISTRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SKIN SMALLINT UNSIGNED NOT NULL,
    SEX BOOLEAN NOT NULL,
    MONEY INT NOT NULL DEFAULT 0,
    XP INT UNSIGNED NOT NULL DEFAULT 0,
    LEVEL SMALLINT UNSIGNED NOT NULL DEFAULT 1,

    HEALTH FLOAT NOT NULL DEFAULT 100.0,
    ARMOR FLOAT NOT NULL DEFAULT 0.0,
    HUNGER FLOAT NOT NULL DEFAULT 0.0,
    THIRST FLOAT NOT NULL DEFAULT 0.0,

    POS_X FLOAT NOT NULL,
    POS_Y FLOAT NOT NULL,
    POS_Z FLOAT NOT NULL,
    ANGLE FLOAT NOT NULL,
    VIRTUAL_WORLD INT NOT NULL DEFAULT 0,
    INTERIOR TINYINT NOT NULL DEFAULT 0,

    ADMIN_LEVEL TINYINT UNSIGNED NOT NULL DEFAULT 0,

    CURRENT_CONNECTION INTEGER UNSIGNED NOT NULL DEFAULT 0,
    PLAYED_TIME INTEGER UNSIGNED NOT NULL DEFAULT 0
);

UPDATE `ACCOUNT` SET `CURRENT_CONNECTION` = 0;

CREATE TABLE IF NOT EXISTS CONNECTION_LOG (
    ACCOUNT_ID INT UNSIGNED NOT NULL,
    IP_ADDRESS VARCHAR(16) NOT NULL,
    DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);