#if defined _KEYNAME_HEADER_
    #endinput
#endif
#define _KEYNAME_HEADER_

enum eKeyInfo {
    bool:e_bKeyActived,
    bool:e_bKeyGoingUp,
    e_iKeyFrameCount,
    e_iKeyTimer
}

new g_rgeKeyData[MAX_PLAYERS + 1][eKeyInfo];

enum {
    KEY_TYPE_FOOT,
    KEY_TYPE_VEHICLE
}

enum eKeyNames {
    KEYNAME_ACTION,
    KEYNAME_CROUCH,
    KEYNAME_FIRE,
    KEYNAME_SPRINT,
    KEYNAME_SECONDARY_ATTACK,
    KEYNAME_JUMP,
    KEYNAME_LOOK_RIGHT,
    KEYNAME_HANDBRAKE,
    KEYNAME_LOOK_LEFT,
    KEYNAME_SUBMISSION,
    KEYNAME_LOOK_BEHIND,
    KEYNAME_WALK,
    KEYNAME_ANALOG_UP,
    KEYNAME_ANALOG_DOWN,
    KEYNAME_ANALOG_LEFT,
    KEYNAME_ANALOG_RIGHT,
    KEYNAME_YES,
    KEYNAME_NO,
    KEYNAME_CTRL_BACK,
    KEYNAME_UP,
    KEYNAME_DOWN,
    KEYNAME_LEFT,
    KEYNAME_RIGHT
}

new g_rgszKeyFootCode[][] = {
    "PED_ANSWER_PHONE",
    "PED_DUCK",
    "PED_FIREWEAPON",
    "PED_SPRINT",
    "VEHICLE_ENTER_EXIT",
    "PED_JUMPING",
    "PED_ANSWER_PHONE", // None
    "PED_LOCK_TARGET",
    "PED_ANSWER_PHONE", // None
    "PED_ANSWER_PHONE", // None
    "PED_LOOKBEHIND",
    "SNEAK_ABOUT",
    "PED_ANSWER_PHONE", // None
    "PED_ANSWER_PHONE", // None
    "VEHICLE_LOOKLEFT",
    "VEHICLE_LOOKRIGHT",
    "CONVERSATION_YES",
    "CONVERSATION_NO",
    "GROUP_CONTROL_BWD",
    "GO_FORWARD",
    "GO_BACK",
    "GO_LEFT",
    "GO_RIGHT"
};

new g_rgszKeyVehicleCode[][] = {
    "VEHICLE_FIREWEAPON_ALT",
    "VEHICLE_HORN",
    "VEHICLE_FIREWEAPON",
    "VEHICLE_ACCELERATE",
    "VEHICLE_ENTER_EXIT",
    "VEHICLE_BRAKE",
    "VEHICLE_LOOKRIGHT",
    "VEHICLE_HANDBRAKE",
    "VEHICLE_LOOKLEFT",
    "TOGGLE_SUBMISSIONS",
    "VEHICLE_LOOKBEHIND",
    "PED_ANSWER_PHONE", // None
    "VEHICLE_TURRETUP",
    "VEHICLE_TURRETDOWN",
    "VEHICLE_TURRETLEFT",
    "VEHICLE_TURRETRIGHT",
    "CONVERSATION_YES",
    "CONVERSATION_NO",
    "GROUP_CONTROL_BWD",
    "VEHICLE_STEERUP",
    "VEHICLE_STEERDOWN",
    "VEHICLE_STEERLEFT",
    "VEHICLE_STEERRIGHT"
};