#if defined _KEYNAME_HEADER_
    #endinput
#endif
#define _KEYNAME_HEADER_

enum eKeyInfo {
    bool:e_bKeyActivated,
    bool:e_bKeyGoingUp,
    e_iKeyFrameCount,
    e_iKeyTimer
}

new g_rgeKeyData[MAX_PLAYERS + 1][eKeyInfo];

enum {
    KEY_TYPE_FOOT,
    KEY_TYPE_VEHICLE
}

enum eKeyNames {
    KEYNAME_ACTION,
    KEYNAME_CROUCH,
    KEYNAME_FIRE,
    KEYNAME_SPRINT,
    KEYNAME_SECONDARY_ATTACK,
    KEYNAME_JUMP,
    KEYNAME_LOOK_RIGHT,
    KEYNAME_HANDBRAKE,
    KEYNAME_LOOK_LEFT,
    KEYNAME_LOOK_BEHIND,
    KEYNAME_SUBMISSION,
    KEYNAME_WALK,
    KEYNAME_ANALOG_UP,
    KEYNAME_ANALOG_DOWN,
    KEYNAME_ANALOG_LEFT,
    KEYNAME_ANALOG_RIGHT,
    KEYNAME_YES,
    KEYNAME_NO,
    KEYNAME_CTRL_BACK,
    KEYNAME_UP,
    KEYNAME_DOWN,
    KEYNAME_LEFT,
    KEYNAME_RIGHT
}

new g_rgszKeyFootCode[][] = {
    "PED_ANSWER_PHONE",     // KEYNAME_ACTION - None
    "PED_DUCK",             // KEYNAME_CROUCH 
    "PED_FIREWEAPON",       // KEYNAME_FIRE
    "PED_SPRINT",           // KEYNAME_SPRINT
    "VEHICLE_ENTER_EXIT",   // KEYNAME_SECONDARY_ATTACK
    "PED_JUMPING",          // KEYNAME_JUMP
    "PED_ANSWER_PHONE",     // KEYNAME_LOOK_RIGHT - None
    "PED_LOCK_TARGET",      // KEYNAME_HANDBRAKE
    "PED_ANSWER_PHONE",     // KEYNAME_LOOK_LEFT - None
    "PED_LOOKBEHIND",       // KEYNAME_LOOK_BEHIND
    "PED_ANSWER_PHONE",     // KEYNAME_SUBMISSION - None
    "SNEAK_ABOUT",          // KEYNAME_WALK
    "PED_ANSWER_PHONE",     // KEYNAME_ANALOG_UP - None
    "PED_ANSWER_PHONE",     // KEYNAME_ANALOG_DOWN - None
    "VEHICLE_LOOKLEFT",     // KEYNAME_ANALOG_LEFT
    "VEHICLE_LOOKRIGHT",    // KEYNAME_ANALOG_RIGHT
    "CONVERSATION_YES",
    "CONVERSATION_NO",
    "GROUP_CONTROL_BWD",
    "GO_FORWARD",
    "GO_BACK",
    "GO_LEFT",
    "GO_RIGHT"
};

new g_rgszKeyVehicleCode[][] = {
    "VEHICLE_FIREWEAPON_ALT",
    "VEHICLE_HORN",
    "VEHICLE_FIREWEAPON",
    "VEHICLE_ACCELERATE",
    "VEHICLE_ENTER_EXIT",
    "VEHICLE_BRAKE",
    "VEHICLE_LOOKRIGHT",
    "VEHICLE_HANDBRAKE",
    "VEHICLE_LOOKLEFT",
    "VEHICLE_LOOKBEHIND",
    "TOGGLE_SUBMISSIONS",
    "PED_ANSWER_PHONE", // None
    "VEHICLE_TURRETUP",
    "VEHICLE_TURRETDOWN",
    "VEHICLE_TURRETLEFT",
    "VEHICLE_TURRETRIGHT",
    "CONVERSATION_YES",
    "CONVERSATION_NO",
    "GROUP_CONTROL_BWD",
    "VEHICLE_STEERUP",
    "VEHICLE_STEERDOWN",
    "VEHICLE_STEERLEFT",
    "VEHICLE_STEERRIGHT"
};

forward Key_Alert(Float:x, Float:y, Float:z, Float:range, key, world = -1, interior = -1, key_type = KEY_TYPE_FOOT, attachedplayer = INVALID_PLAYER_ID, callback_on_press = -1);
