#if defined _weather_header_
    #endinput
#endif
#define _weather_header_

const HYAXE_WEATHER_INTERVAL = 120000; // Default: 120000

enum eWeatherType
{
    WEATHER_EXTRASUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_CLOUDY_LA,
    WEATHER_SUNNY_SF,
    WEATHER_EXTRASUNNY_SF,
    WEATHER_CLOUDY_SF,
    WEATHER_RAINY_SF,
    WEATHER_FOGGY_SF,
    WEATHER_SUNNY_VEGAS,
    WEATHER_EXTRASUNNY_VEGAS, // (heat waves)
    WEATHER_CLOUDY_VEGAS,
    WEATHER_EXTRASUNNY_COUNTRYSIDE,
    WEATHER_SUNNY_COUNTRYSIDE,
    WEATHER_CLOUDY_COUNTRYSIDE,
    WEATHER_RAINY_COUNTRYSIDE,
    WEATHER_EXTRASUNNY_DESERT,
    WEATHER_SUNNY_DESERT,
    WEATHER_SANDSTORM_DESERT,
    WEATHER_UNDERWATER // (greenish, foggy)
};

new const eWeatherType:g_iWeatherTypesList[] =
{
    WEATHER_SUNNY_LA,
    WEATHER_RAINY_SF,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_RAINY_SF,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_RAINY_COUNTRYSIDE,
    WEATHER_RAINY_COUNTRYSIDE,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_RAINY_SF,
    WEATHER_SUNNY_LA,
    WEATHER_SANDSTORM_DESERT,
    WEATHER_RAINY_SF,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA
};

new g_iWeatherType = 1;

forward Timer_WeatherUpdate();