#if defined _weather_header_
    #endinput
#endif
#define _weather_header_

enum eWeatherType
{
    WEATHER_UNDEFINED = -1,

    WEATHER_EXTRASUNNY_LA = 0,
    WEATHER_SUNNY_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_CLOUDY_LA,

    WEATHER_RAINY_COUNTRYSIDE = 16
};

new const eWeatherType:s_iWeatherTypesListLA[] =
{
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_CLOUDY_LA,
    WEATHER_CLOUDY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_SUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_RAINY_COUNTRYSIDE,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_CLOUDY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_SUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA,
    WEATHER_EXTRASUNNY_SMOG_LA
};

new
    s_iClockUpdateTimer,

    s_iMsPerClockMinute,
    s_iLastClockTick,

    s_iClockSeconds,
    s_iClockMinutes,

    bool:s_bClockSyncToggled,
    bool:s_bPlayerClockSyncToggled[MAX_PLAYERS char],

    s_iWeatherTypeInList,
    eWeatherType:s_iOldWeatherType,
    eWeatherType:s_iNewWeatherType,
    eWeatherType:s_iForcedWeatherType,    

    eWeatherType:s_iPlayerForcedWeather[MAX_PLAYERS],

    bool:s_bPlayerClockToggled[MAX_PLAYERS char]
;

forward Timer_ClockUpdate();
//forward OnWeatherTypeChange(newweather, oldweather);

#define Weather_IsReleased !Weather_IsForced
